#!/bin/sh
set -e -u -x
cd "$(dirname "$0")"
basedir=$PWD
workdir=$(mktemp -d)
trap 'cd $basedir && rm -r $workdir' EXIT
cd "$workdir"
cmake "$basedir"
make -j"$(getconf _NPROCESSORS_ONLN)"

mkdir test1
cd test1
../record/zlib-record python3 -c 'import zlib; zlib.compress(b"abc")'
../replay/zlib-replay deflate.*.0
